WITH COLUMN_DATA AS (SELECT COLUMN_NAME, DATA_TYPE, TABLE_NAME, TABLE_SCHEMA
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME='$table_name' AND TABLE_SCHEMA='$schema_name'),
PK_INDICATOR AS (SELECT COLUMN_NAME, 1 as PKflag,  TABLE_NAME, TABLE_SCHEMA
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_SCHEMA + '.' + QUOTENAME(CONSTRAINT_NAME)), 'IsPrimaryKey') = 1
AND TABLE_NAME = '$table_name' AND TABLE_SCHEMA = '$schema_name'), T_PREVIA AS(
SELECT COLUMN_DATA.COLUMN_NAME, COLUMN_DATA.DATA_TYPE,
	CASE WHEN COLUMN_DATA.COLUMN_NAME = PK_INDICATOR.COLUMN_NAME THEN PK_INDICATOR.PKflag
	ELSE 0
	END AS PKflag
FROM COLUMN_DATA 
JOIN PK_INDICATOR on PK_INDICATOR.TABLE_NAME = COLUMN_DATA.TABLE_NAME 
AND PK_INDICATOR.TABLE_SCHEMA = COLUMN_DATA.TABLE_SCHEMA)
SELECT * FROM T_PREVIA 
WHERE T_PREVIA.PKflag=1